name: contentful
version: 1.0.0
author: ARISE Church <it@arisechurch.com>
homepage: https://arisechurch.com
description: Contentful Delivery API client for Dart.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  equatable: ^0.2.4
  http: ^0.12.0
  json_annotation: ^2.4.0
  meta: ^1.1.6

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
